Username: 1710555219@qq.com
Password: Niubidalaocc666

Satellites:
  Telesat:
    Name: Telesat
    Query: /OBJECT_NAME/TELESAT~~/orderby/epoch%20desc/format/tle
  GlobalStar:
    Name: GlobalStar
    Query: /OBJECT_NAME/GLOBALSTAR~~/orderby/epoch%20desc/format/tle
  Iridium:
    Name: Iridium
    Query: /OBJECT_NAME/IRIDIUM~~/orderby/epoch%20desc/format/tle
  Starlink:
    Name: Starlink
    Query: /OBJECT_NAME/STARLINK~~/orderby/epoch%20desc/format/tle
  Kuiper:
    Name: Kuiper
    Query: /OBJECT_NAME/KUIPER~~/orderby/epoch%20desc/format/tle
  OneWeb:
    Name: OneWeb
    Query: /OBJECT_NAME/ONEWEB~~/orderby/epoch%20desc/format/tle
